import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import TawkToWidget from './components/TawkToWidget';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const googleAnalyticsId = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS;
  const enableGA = process.env.NEXT_PUBLIC_ENABLE_GA === 'true';
  
  return (
    <html lang="en" >
      <head>
      <title>LaNuit Tech | Elevate your online presence </title>
      <link rel="icon" href="/logo4.png" type="image/x-icon" sizes="30x30" />
        {/* Conditional Google Analytics */}
        {enableGA && googleAnalyticsId && (
          <>
            <script async src={`https://www.googletagmanager.com/gtag/js?id=${googleAnalyticsId}`}></script>
            <script
              dangerouslySetInnerHTML={{
                __html: `
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);}
                  gtag('js', new Date());
                  gtag('config', '${googleAnalyticsId}');
                `,
              }}
            />
          </>
        )}
      </head>
      

      <body className={inter.className}>
        <div id='blurry-ball'></div>
        <div id='blurry-pink-ball'></div>
      
      
      
        <div id='blurry-ball2' className='hidden md:block'></div>
        <div id='blurry-pink-ball2' className='hidden md:block'></div>
        <div id='blurry-ball3'></div>
        <div id='blurry-pink-ball3'></div>



        
          <Navbar />
          {children}
          <Footer />
          <TawkToWidget />
            
      </body>
  
    </html >
  )
}
